install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("remotes")
remotes::install_github(repo = "speegled/fosdata")
install.packages("sf")
install.packages("terra")
install.packages("spData")
